# Heuristics Constants
MANHATTAN_HEURISTICS = 0
EUCLIDEAN_HEURISTICS = 1
CHEBYSHEV_HEURISTICS = 2
COMBINED_HEURISTICS = 3

# Field of view flag
ALLOW_FIELD_OF_VIEW = 0
RESTRICT_FIELD_OF_VIEW = 1
ALLOW_BASIC_SENSING = 2
ALLOW_ADVANCED_SENSING = 3

# Search type
A_STAR = 0
BFS = 1

# global properties
GLOBAL_PROBABILITY = 0.35
GLOBAL_BIG_MAZE_SIZE = 101
GLOBAL_SMALL_MAZE_SIZE = 10
GLOBAL_TEST_COUNT = 50

# sensed states
EMPTY_STATE = 0
BLOCKED_STATE = 1
UNCERTAIN_STATE = 2

